
spring.application.name=springbootwebtutorial

server.port=8081

spring.h2.console.enabled=true
spring.datasource.url= jdbc:h2:file:C:/Users/KIIT/Documents/tutorialDB/db
spring.datasource.username=SnehajitDB
spring.datasource.password=snehajit123
spring.jpa.hibernate.ddl-auto=create